import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const APP_BASE_URL="https://atelierog.co.in/gym-manager";
const esc=(v:string)=>String(v??"").replace(/[&<>\"]/g,(m)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]||m));
const slugify=(v:string)=>String(v||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,60)||"gym";
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});
 if(req.method!=="POST")return Response.json({error:"Method not allowed"},{status:405,headers:CORS});
 const auth=req.headers.get("Authorization");if(!auth)return Response.json({error:"Unauthorized"},{status:401,headers:CORS});
 const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const token=auth.replace("Bearer ","");const{data:{user:actor},error:ae}=await admin.auth.getUser(token);if(ae||!actor)return Response.json({error:"Unauthorized"},{status:401,headers:CORS});
 const{data:ap}=await admin.from("profiles").select("gym_id,role").eq("id",actor.id).single();if(!ap||ap.role!=="admin")return Response.json({error:"Admin access required"},{status:403,headers:CORS});
 const b=await req.json();const email=String(b.email||"").trim().toLowerCase();if(!email)return Response.json({sent:false,reason:"No email address supplied"},{headers:{...CORS,"Content-Type":"application/json"}});
 const key=Deno.env.get("RESEND_API_KEY");if(!key)return Response.json({sent:false,reason:"RESEND_API_KEY is not configured"},{headers:{...CORS,"Content-Type":"application/json"}});
 const{data:gym}=await admin.from("gyms").select("name,slug").eq("id",ap.gym_id).single();const gymName=String(gym?.name||b.gym_name||"Gym"),slug=String(gym?.slug||slugify(gymName)),roleUrl=`${APP_BASE_URL}/${slug}/trainer`,name=String(b.trainer_name||"Trainer"),loginId=String(b.login_id||""),password=String(b.password||"");
 const from=Deno.env.get("GYMOS_FROM_EMAIL")||"Atelier OG Gym Manager <noreply@atelierog.co.in>";const subject=`Welcome to Gym Manager — ${gymName}`;
 const html=`<div style="margin:0;background:#f3f4f6;padding:32px 12px;font-family:Arial,Helvetica,sans-serif;color:#111827"><div style="max-width:640px;margin:auto;background:#fff;border:1px solid #e5e7eb;border-radius:18px;overflow:hidden"><div style="background:#0e1626;color:#fff;padding:30px 34px"><div style="font-size:26px;font-weight:800;letter-spacing:1px">GYM MANAGER</div><div style="margin-top:7px;font-size:12px;letter-spacing:2px;color:#cbd5e1">BY ATELIER OG</div></div><div style="height:4px;background:#c99528"></div><div style="padding:32px 34px"><p style="font-size:20px;font-weight:700;margin:0 0 8px">Welcome, ${esc(name)}!</p><p style="color:#6b7280;line-height:1.6">You have been added as a <strong>Trainer</strong> at ${esc(gymName)}.</p><div style="background:#0e1626;color:#fff;border-radius:14px;padding:22px;margin:24px 0"><div style="font-size:11px;letter-spacing:1.5px;color:#cbd5e1;font-weight:700">TRAINER LOGIN</div><p>Login ID<br><strong>${esc(loginId)}</strong></p><p>Temporary password<br><strong>${esc(password)}</strong></p></div><div style="text-align:center"><a href="${esc(roleUrl)}" style="display:inline-block;background:#0e1626;color:#fff;text-decoration:none;padding:13px 24px;border-radius:10px;font-weight:700">Open Gym Manager</a><div style="margin-top:10px;font-size:11px;color:#6b7280;word-break:break-all">${esc(roleUrl)}</div></div><p style="margin-top:24px;font-size:12px;color:#6b7280">This link opens the Trainer login for ${esc(gymName)}. Please change your temporary password after your first login.</p></div><div style="padding:18px 34px;background:#f8fafc;color:#9ca3af;font-size:11px">Atelier OG Gym Manager • Business management system</div></div></div>`;
 const rr=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Authorization":"Bearer "+key,"Content-Type":"application/json","Idempotency-Key":"gym-manager-trainer-welcome-"+String(b.user_id||loginId||actor.id)},body:JSON.stringify({from,to:[email],subject,html})});if(!rr.ok)return Response.json({sent:false,error:await rr.text()},{status:502,headers:CORS});const result=await rr.json();return Response.json({sent:true,id:result?.id||null,role_login_url:roleUrl},{headers:{...CORS,"Content-Type":"application/json"}});
});
