import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./app.css";import{supabase}from"./lib/supabase";import{currentProfile,signOut}from"./lib/auth";import Login from"./login";

function Card({t,n,s}){return <article><small>{t}</small><strong>{n}</strong><span>{s}</span></article>}
function Dashboard({profile}){
 return <div className="app"><aside><h1>GYM<span>OS</span></h1><p>{profile?.full_name||"Gym"} · {profile?.role||"user"}</p><nav>{["Dashboard","Members","Attendance","Payments","Reports","Settings"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</nav><button className="logout" onClick={signOut}>Sign out</button></aside><main><header><div><small>GYM MANAGEMENT SYSTEM</small><h2>Dashboard</h2></div><button className="primary">+ Add Member</button></header><section className="cards"><Card t="Total members" n="0" s="Live database"/><Card t="Active" n="0" s="Membership valid"/><Card t="Expiring soon" n="0" s="Next 7 days"/><Card t="Today's collection" n="₹0" s="Live database"/></section><div className="columns"><section className="panel"><h3>Today's attendance</h3><strong className="number">0</strong><span> present</span><p>Live attendance will appear here.</p></section><section className="panel"><h3>Membership alerts</h3><p>Expiry alerts will appear here.</p><p>Notifications are being connected to the database.</p></section></div><section className="panel"><h3>Signed in</h3><p>You are authenticated as <b>{profile?.login_id}</b> with role <b>{profile?.role}</b>.</p><p>Tenant isolation is enforced by PostgreSQL Row Level Security.</p></section></main></div>
}
function App(){const[profile,setProfile]=useState(undefined);useEffect(()=>{(async()=>{if(!supabase){setProfile(null);return}try{setProfile(await currentProfile())}catch{setProfile(null)}})()},[]);useEffect(()=>{if(!supabase)return;const{data}=supabase.auth.onAuthStateChange(async()=>{try{setProfile(await currentProfile())}catch{setProfile(null)}});return()=>data.subscription.unsubscribe()},[]);if(profile===undefined)return <div className="login"><div className="login-card"><h1>GYM<span>OS</span></h1><p>Loading…</p></div></div>;return profile?<Dashboard profile={profile}/>:<Login onLogin={async()=>setProfile(await currentProfile())}/>}

createRoot(document.getElementById("root")).render(<App/>);
